version: '3'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
#  production_traefik: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: kale_production_django
    volumes:
      - /var/www/kale.abba.uz/media:/app/media
      - /var/www/kale.abba.uz/static:/app/static
    depends_on:
      - postgres
      - redis
    ports:
      - 7000:7000
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kale_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres


  docs:
    <<: *django
    image: kale_local_docs
    container_name: kale_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./kale:/app/kale:z
      - ./common:/app/common:z
    ports:
      - '9000:9000'
    command: /start-docs

  #  traefik:
  #    build:
  #      context: .
  #      dockerfile: ./compose/production/traefik/Dockerfile
  #    image: kale_production_traefik
  #    depends_on:
  #      - django
  #    volumes:
  #      - production_traefik:/etc/traefik/acme
  #    ports:
  #      - '0.0.0.0:80:80'
  #      - '0.0.0.0:443:443'
  #      - '0.0.0.0:5555:5555'

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: kale_production_celeryworker
    container_name: kale_production_celeryworker
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: kale_production_celerybeat
    container_name: kale_production_celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat

  #  flower:
  #    <<: *django
  #    image: kale_production_flower
  #    ports:
  #      - '5555:5555'
  #    command: /start-flower

#  nginx:
#    build:
#      context: .
#      dockerfile: ./compose/production/nginx/Dockerfile
#    image: kale_nginx
#    depends_on:
#      - django
#    volumes:
#      #      - production_django_media:/usr/share/nginx/media:ro
#      - .:/app:cached
#      - static_volume:/app/static
#      - media_volume:/app/media
#    ports:
#      - 80:80
#      - 443:443
