# Generated by Django 4.2.3 on 2023-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="file3D",
            field=models.URLField(blank=True, null=True),
        ),
    ]
