# Generated by Django 4.2.3 on 2023-08-21 17:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_alter_portfolio_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description_ru",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description_uz",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title_en",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title_ru",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title_uz",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
