# Generated by Django 4.2.3 on 2023-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_portfolio_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name="Image for logo Portfolio"),
        ),
        migrations.AddField(
            model_name="portfolioimage",
            name="title",
            field=models.CharField(default="Interior photo", max_length=50),
        ),
    ]
