# Generated by Django 4.2.3 on 2023-07-22 12:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("location", models.TextField()),
                ("isMap", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
