# Generated by Django 4.2.3 on 2023-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_map_delete_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="location",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="social",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="social",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
