# Generated by Django 4.2.3 on 2023-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_social_location_social_phone_social_youtube"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="text_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="title_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="title_ru",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="title_uz",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
