# Generated by Django 4.2.3 on 2023-08-16 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_map_text_en_map_text_ru_map_text_uz_map_title_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.URLField()),
                ("phone", models.CharField(max_length=14)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="social",
            name="location",
        ),
        migrations.RemoveField(
            model_name="social",
            name="phone",
        ),
        migrations.CreateModel(
            name="FilialImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="filialImage", verbose_name="Image of Filial"),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="filialImages", to="social.filial"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="filial",
            name="social",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="filial", to="social.social"
            ),
        ),
    ]
