# Generated by Django 4.2.3 on 2023-08-17 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_filial_remove_social_location_remove_social_phone_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FilialImage",
        ),
    ]
