# Generated by Django 4.2.3 on 2023-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_delete_filialimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="location",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filial",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="text_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="text_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="title_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="title_uz",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
