# Generated by Django 4.2.3 on 2023-09-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0008_alter_filial_location_alter_filial_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
