# Generated by Django 4.2.3 on 2023-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_description_en_news_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="videoURL",
            field=models.URLField(blank=True, null=True),
        ),
    ]
