# Generated by Django 4.2.3 on 2023-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news_videourl"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="viewCount",
            field=models.IntegerField(default=0),
        ),
    ]
