# Generated by Django 4.2.3 on 2023-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_news_viewcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
