# Generated by Django 4.2.3 on 2023-08-18 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-id"]},
        ),
    ]
