# Generated by Django 4.2.3 on 2023-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_news_description_alter_news_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="isActual",
            field=models.BooleanField(default=False),
        ),
    ]
