# Generated by Django 4.2.3 on 2023-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymeuz', '0003_remove_transaction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
