# Generated by Django 4.2.3 on 2023-09-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="bannerImage", verbose_name="Image of Banner"),
        ),
        migrations.AddField(
            model_name="banner",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to="bannerImage", verbose_name="Image of Banner"),
        ),
        migrations.AddField(
            model_name="smallbanner",
            name="photo2",
            field=models.ImageField(
                blank=True, null=True, upload_to="smallBannerImage", verbose_name="Image of SmallBanner"
            ),
        ),
        migrations.AddField(
            model_name="smallbanner",
            name="photo3",
            field=models.ImageField(
                blank=True, null=True, upload_to="smallBannerImage", verbose_name="Image of SmallBanner"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="bannerImage", verbose_name="Image of Banner"),
        ),
        migrations.AlterField(
            model_name="smallbanner",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="smallBannerImage", verbose_name="Image of SmallBanner"
            ),
        ),
    ]
