# Generated by Django 4.2.3 on 2023-10-15 17:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0002_banner_photo2_banner_photo3_smallbanner_photo2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
