# Generated by Django 4.2.3 on 2023-10-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0003_headerdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="headerdiscount",
            name="text_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="headerdiscount",
            name="text_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="headerdiscount",
            name="text_uz",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
