# Generated by Django 4.2.3 on 2023-10-23 17:47

from django.db import migrations, models


def delete_objects(apps, schema_editor):
    HeaderDiscount = apps.get_model('banner', 'HeaderDiscount')
    # Replace <app_name> with the name of your Django app
    # Replace <model_name> with the name of the model you want to create objects for
    HeaderDiscount.objects.all().delete()


def reverse_delete_objects(apps, schema_editor):
    # Object removal code
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0004_headerdiscount_text_en_headerdiscount_text_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headerdiscount",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(delete_objects, reverse_delete_objects),
    ]
