# Generated by Django 4.2.3 on 2023-08-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_order_status"),
        ("payme", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="orders",
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderPayment",
                to="order.order",
            ),
        ),
    ]
