# Generated by Django 4.2.3 on 2023-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payme", "0002_remove_payment_discount_remove_payment_orders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paymentType",
            field=models.IntegerField(choices=[(1, "PAYME"), (2, "CLICK")]),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "WAITING"),
                    (2, "PREAUTH"),
                    (3, "CONFIRMED"),
                    (4, "REJECTED"),
                    (5, "REFUNDED"),
                    (6, "ERROR"),
                ],
                default=1,
            ),
        ),
    ]
