# Generated by Django 4.2.3 on 2023-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payme", "0003_alter_payment_paymenttype_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "WAITING"),
                    ("preauth", "PREAUTH"),
                    ("confirmed", "CONFIRMED"),
                    ("rejected", "REJECTED"),
                    ("refunded", "REFUNDED"),
                    ("error", "ERROR"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
