# Generated by Django 4.2.3 on 2023-07-24 12:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="categoryImage", verbose_name="Image of Category")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=250)),
                ("description", ckeditor.fields.RichTextField()),
                ("price", models.FloatField(default=0)),
                ("material", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[("м2", "м2"), ("шт", "шт"), ("комп", "комп")], default="шт", max_length=5
                    ),
                ),
                ("file3D", models.URLField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.CharField(blank=True, max_length=30, null=True)),
                ("manufacturer", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="productImage", verbose_name="Image of Product"
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("discount", models.FloatField(default=0)),
                ("isTop", models.BooleanField(default=False, verbose_name="Is Top")),
                (
                    "cornerStatus",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "NEWS"),
                            (2, "DISCOUNT"),
                            (3, "SPECIAL"),
                            (4, "RECOMMENDATION"),
                            (5, "CHEAP"),
                            (6, "EXPENSIVE"),
                            (7, "POPULAR"),
                        ],
                        null=True,
                    ),
                ),
                ("status", models.IntegerField(choices=[(1, "DRAFT"), (2, "ACTIVE"), (3, "DELETED")], default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorySubCategory",
                        to="product.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="productImage", verbose_name="Image of Product"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="productImages", to="product.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategoryProducts",
                to="product.subcategory",
            ),
        ),
    ]
