# Generated by Django 4.2.3 on 2023-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="categoryImage", verbose_name="Image of Category"
            ),
        ),
    ]
