# Generated by Django 4.2.3 on 2023-08-09 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_category_title_en_category_title_ru_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="subcategory",
        ),
    ]
