# Generated by Django 4.2.3 on 2023-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="oldPrice",
            field=models.FloatField(default=0),
        ),
    ]
