# Generated by Django 4.2.3 on 2023-10-17 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_product_oldprice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="oldPrice",
            new_name="discountPrice",
        ),
    ]
