# Generated by Django 4.2.3 on 2023-10-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_rename_oldprice_product_discountprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discountPrice",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
