# Generated by Django 4.2.3 on 2023-08-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_portfolio_catalogimage_catalog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogimage",
            name="imageURL",
        ),
        migrations.AddField(
            model_name="catalogimage",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="catalogImage", verbose_name="Image of Product"),
        ),
    ]
