# Generated by Django 4.2.3 on 2023-08-18 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_remove_catalogimage_imageurl_catalogimage_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalog",
            options={"ordering": ["-id"]},
        ),
    ]
