# Generated by Django 4.2.3 on 2023-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_catalog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="title_en",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="title_ru",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="title_uz",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
