# Generated by Django 4.2.3 on 2023-08-22 05:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_catalog_title_alter_catalog_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="description_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="description_ru",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="description_uz",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
