#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage_prod.py collectstatic --noinput
python /app/manage_prod.py migrate

exec /usr/local/bin/uvicorn config.asgi:application --host 0.0.0.0 --port 7000 --app-dir=/app
