# Generated by Django 4.2.3 on 2023-08-18 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-id"]},
        ),
    ]
