# Generated by Django 4.2.3 on 2023-08-17 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_category_product_subcategory"),
        ("order", "0004_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField(default=1)),
                ("orderPrice", models.FloatField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orderProduct", to="product.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="isDelivery",
            new_name="installation",
        ),
        migrations.RemoveField(
            model_name="order",
            name="checkout",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentStatus",
            field=models.IntegerField(
                choices=[(1, "NOT_PAID"), (2, "WAITING"), (3, "CANCELED"), (4, "ABORTED"), (5, "PAID")], default=1
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentType",
            field=models.IntegerField(choices=[(1, "PAYME"), (2, "CLICK"), (3, "UZUM"), (4, "CASH")], default=4),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "PENDING"),
                    (2, "WAITING"),
                    (3, "DELIVERED"),
                    (4, "CANCELED"),
                    (5, "IN_PROGRESS"),
                    (6, "DELETED"),
                    (7, "PAYMENT"),
                ],
                default=7,
            ),
        ),
        migrations.DeleteModel(
            name="Checkout",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(blank=True, related_name="orderedProducts", to="order.orderproduct"),
        ),
    ]
