# Generated by Django 4.2.3 on 2023-08-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
        ("order", "0006_order_code_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderAddress",
                to="address.address",
            ),
        ),
    ]
