# Generated by Django 4.2.3 on 2023-08-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_category_product_subcategory"),
        ("order", "0008_alter_orderproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.product"),
        ),
    ]
