# Generated by Django 4.2.3 on 2023-08-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_orderproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="orderPrice",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
