# Generated by Django 4.2.3 on 2023-08-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_orderproduct_orderprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "PAYMENT"),
                    (1, "PENDING"),
                    (2, "WAITING"),
                    (3, "DELIVERED"),
                    (4, "CANCELED"),
                    (5, "IN_PROGRESS"),
                    (6, "DELETED"),
                ],
                default=0,
            ),
        ),
    ]
