# Generated by Django 4.2.3 on 2023-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_orderproduct_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paymentStatus",
            field=models.IntegerField(
                choices=[
                    (1, "WAITING"),
                    (2, "PREAUTH"),
                    (3, "CONFIRMED"),
                    (4, "REJECTED"),
                    (5, "REFUNDED"),
                    (6, "ERROR"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.IntegerField(choices=[(1, "PAYME"), (2, "CLICK"), (3, "CASH")], default=3),
        ),
    ]
