# Generated by Django 4.2.3 on 2023-11-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_district_region_street_district_region"),
        ("order", "0016_alter_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderDistrict",
                to="address.district",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderRegion",
                to="address.region",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderStreet",
                to="address.district",
            ),
        ),
    ]
